// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATGIDH_9eBbgJ25BQv0FrgnHSMP7HpRWA',
    appId: '1:162587604834:web:7ce7b24e6c280f3b195e3b',
    messagingSenderId: '162587604834',
    projectId: 'airticket-7a246',
    authDomain: 'airticket-7a246.firebaseapp.com',
    storageBucket: 'airticket-7a246.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBT0Uq-e4MrcoQXTjAAg_Ak_zCxsPa7Fn4',
    appId: '1:162587604834:android:bc69dfb5ed0477ee195e3b',
    messagingSenderId: '162587604834',
    projectId: 'airticket-7a246',
    storageBucket: 'airticket-7a246.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxnsdWql4srS9a7VOFzC_NnkJkYRSj4bg',
    appId: '1:162587604834:ios:82f7b64a664f91a1195e3b',
    messagingSenderId: '162587604834',
    projectId: 'airticket-7a246',
    storageBucket: 'airticket-7a246.firebasestorage.app',
    iosBundleId: 'com.example.powerapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxnsdWql4srS9a7VOFzC_NnkJkYRSj4bg',
    appId: '1:162587604834:ios:82f7b64a664f91a1195e3b',
    messagingSenderId: '162587604834',
    projectId: 'airticket-7a246',
    storageBucket: 'airticket-7a246.firebasestorage.app',
    iosBundleId: 'com.example.powerapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATGIDH_9eBbgJ25BQv0FrgnHSMP7HpRWA',
    appId: '1:162587604834:web:94885163385d261e195e3b',
    messagingSenderId: '162587604834',
    projectId: 'airticket-7a246',
    authDomain: 'airticket-7a246.firebaseapp.com',
    storageBucket: 'airticket-7a246.firebasestorage.app',
  );
}
