final List<String> countries = [
  'Afghanistan',
  'Albania',
  'Algeria',
  'Andorra',
  'Angola',
  'Antigua and Barbuda',
  'Argentina',
  'Armenia',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Bahamas',
  'Bahrain',
  'Bangladesh',
  'Barbados',
  'Belarus',
  'Belgium',
  'Belize',
  'Benin',
  'Bhutan',
  'Bolivia',
  'Bosnia and Herzegovina',
  'Botswana',
  'Brazil',
  'Brunei',
  'Bulgaria',
  'Burkina Faso',
  'Burundi',
  'Cabo Verde',
  'Cambodia',
  'Cameroon',
  'Canada',
  'Central African Republic',
  'Chad',
  'Chile',
  'China',
  'Colombia',
  'Comoros',
  'Congo (Congo-Brazzaville)',
  'Costa Rica',
  'Croatia',
  'Cuba',
  'Cyprus',
  'Czechia (Czech Republic)',
  'Denmark',
  'Djibouti',
  'Dominica',
  'Dominican Republic',
  'Ecuador',
  'Egypt',
  'El Salvador',
  'Equatorial Guinea',
  'Eritrea',
  'Estonia',
  'Eswatini (fmr. "Swaziland")',
  'Ethiopia',
  'Fiji',
  'Finland',
  'France',
  'Gabon',
  'Gambia',
  'Georgia',
  'Germany',
  'Ghana',
  'Greece',
  'Grenada',
  'Guatemala',
  'Guinea',
  'Guinea-Bissau',
  'Guyana',
  'Haiti',
  'Holy See',
  'Honduras',
  'Hungary',
  'Iceland',
  'India',
  'Indonesia',
  'Iran',
  'Iraq',
  'Ireland',
  'Israel',
  'Italy',
  'Jamaica',
  'Japan',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'Kiribati',
  'Kuwait',
  'Kyrgyzstan',
  'Laos',
  'Latvia',
  'Lebanon',
  'Lesotho',
  'Liberia',
  'Libya',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Madagascar',
  'Malawi',
  'Malaysia',
  'Maldives',
  'Mali',
  'Malta',
  'Marshall Islands',
  'Mauritania',
  'Mauritius',
  'Mexico',
  'Micronesia',
  'Moldova',
  'Monaco',
  'Mongolia',
  'Montenegro',
  'Morocco',
  'Mozambique',
  'Myanmar (formerly Burma)',
  'Namibia',
  'Nauru',
  'Nepal',
  'Netherlands',
  'New Zealand',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'North Korea',
  'North Macedonia (formerly Macedonia)',
  'Norway',
  'Oman',
  'Pakistan',
  'Palau',
  'Palestine State',
  'Panama',
  'Papua New Guinea',
  'Paraguay',
  'Peru',
  'Philippines',
  'Poland',
  'Portugal',
  'Qatar',
  'Romania',
  'Russia',
  'Rwanda',
  'Saint Kitts and Nevis',
  'Saint Lucia',
  'Saint Vincent and the Grenadines',
  'Samoa',
  'San Marino',
  'Sao Tome and Principe',
  'Saudi Arabia',
  'Senegal',
  'Serbia',
  'Seychelles',
  'Sierra Leone',
  'Singapore',
  'Slovakia',
  'Slovenia',
  'Solomon Islands',
  'Somalia',
  'South Africa',
  'South Korea',
  'South Sudan',
  'Spain',
  'Sri Lanka',
  'Sudan',
  'Suriname',
  'Sweden',
  'Switzerland',
  'Syria',
  'Tajikistan',
  'Tanzania',
  'Thailand',
  'Timor-Leste',
  'Togo',
  'Tonga',
  'Trinidad and Tobago',
  'Tunisia',
  'Turkey',
  'Turkmenistan',
  'Tuvalu',
  'Uganda',
  'Ukraine',
  'United Arab Emirates',
  'United Kingdom',
  'United States of America',
  'Uruguay',
  'Uzbekistan',
  'Vanuatu',
  'Venezuela',
  'Vietnam',
  'Yemen',
  'Zambia',
  'Zimbabwe',
];

final List<Map<String, String>> abbreviatedCountries = [
  {"name": "Afghanistan", "code": "AFG"},
  {"name": "Albania", "code": "ALB"},
  {"name": "Algeria", "code": "DZA"},
  {"name": "Andorra", "code": "AND"},
  {"name": "Angola", "code": "AGO"},
  {"name": "Antigua and Barbuda", "code": "ATG"},
  {"name": "Argentina", "code": "ARG"},
  {"name": "Armenia", "code": "ARM"},
  {"name": "Australia", "code": "AUS"},
  {"name": "Austria", "code": "AUT"},
  {"name": "Azerbaijan", "code": "AZE"},
  {"name": "Bahamas", "code": "BHS"},
  {"name": "Bahrain", "code": "BHR"},
  {"name": "Bangladesh", "code": "BGD"},
  {"name": "Barbados", "code": "BRB"},
  {"name": "Belarus", "code": "BLR"},
  {"name": "Belgium", "code": "BEL"},
  {"name": "Belize", "code": "BLZ"},
  {"name": "Benin", "code": "BEN"},
  {"name": "Bhutan", "code": "BTN"},
  {"name": "Bolivia", "code": "BOL"},
  {"name": "Bosnia and Herzegovina", "code": "BIH"},
  {"name": "Botswana", "code": "BWA"},
  {"name": "Brazil", "code": "BRA"},
  {"name": "Brunei", "code": "BRN"},
  {"name": "Bulgaria", "code": "BGR"},
  {"name": "Burkina Faso", "code": "BFA"},
  {"name": "Burundi", "code": "BDI"},
  {"name": "Cambodia", "code": "KHM"},
  {"name": "Cameroon", "code": "CMR"},
  {"name": "Canada", "code": "CAN"},
  {"name": "Central African Republic", "code": "CAF"},
  {"name": "Chad", "code": "TCD"},
  {"name": "Chile", "code": "CHL"},
  {"name": "China", "code": "CHN"},
  {"name": "Colombia", "code": "COL"},
  {"name": "Comoros", "code": "COM"},
  {"name": "Congo", "code": "COG"},
  {"name": "Costa Rica", "code": "CRI"},
  {"name": "Côte d'Ivoire", "code": "CIV"},
  {"name": "Croatia", "code": "HRV"},
  {"name": "Cuba", "code": "CUB"},
  {"name": "Cyprus", "code": "CYP"},
  {"name": "Czech Republic", "code": "CZE"},
  {"name": "Denmark", "code": "DNK"},
  {"name": "Djibouti", "code": "DJI"},
  {"name": "Dominica", "code": "DMA"},
  {"name": "Dominican Republic", "code": "DOM"},
  {"name": "Ecuador", "code": "ECU"},
  {"name": "Egypt", "code": "EGY"},
  {"name": "El Salvador", "code": "SLV"},
  {"name": "Equatorial Guinea", "code": "GNQ"},
  {"name": "Eritrea", "code": "ERI"},
  {"name": "Estonia", "code": "EST"},
  {"name": "Ethiopia", "code": "ETH"},
  {"name": "Fiji", "code": "FJI"},
  {"name": "Finland", "code": "FIN"},
  {"name": "France", "code": "FRA"},
  {"name": "Gabon", "code": "GAB"},
  {"name": "Gambia", "code": "GMB"},
  {"name": "Georgia", "code": "GEO"},
  {"name": "Germany", "code": "DEU"},
  {"name": "Ghana", "code": "GHA"},
  {"name": "Greece", "code": "GRC"},
  {"name": "Grenada", "code": "GRD"},
  {"name": "Guatemala", "code": "GTM"},
  {"name": "Guinea", "code": "GIN"},
  {"name": "Guinea-Bissau", "code": "GNB"},
  {"name": "Guyana", "code": "GUY"},
  {"name": "Haiti", "code": "HTI"},
  {"name": "Honduras", "code": "HND"},
  {"name": "Hungary", "code": "HUN"},
  {"name": "Iceland", "code": "ISL"},
  {"name": "India", "code": "IND"},
  {"name": "Indonesia", "code": "IDN"},
  {"name": "Iran", "code": "IRN"},
  {"name": "Iraq", "code": "IRQ"},
  {"name": "Ireland", "code": "IRL"},
  {"name": "Israel", "code": "ISR"},
  {"name": "Italy", "code": "ITA"},
  {"name": "Jamaica", "code": "JAM"},
  {"name": "Japan", "code": "JPN"},
  {"name": "Jordan", "code": "JOR"},
  {"name": "Kazakhstan", "code": "KAZ"},
  {"name": "Kenya", "code": "KEN"},
  {"name": "Kiribati", "code": "KIR"},
  {"name": "Korea (North)", "code": "PRK"},
  {"name": "Korea (South)", "code": "KOR"},
  {"name": "Kosovo", "code": "XKX"},
  {"name": "Kuwait", "code": "KWT"},
  {"name": "Kyrgyzstan", "code": "KGZ"},
  {"name": "Laos", "code": "LAO"},
  {"name": "Latvia", "code": "LVA"},
  {"name": "Lebanon", "code": "LBN"},
  {"name": "Lesotho", "code": "LSO"},
  {"name": "Liberia", "code": "LBR"},
  {"name": "Libya", "code": "LBY"},
  {"name": "Liechtenstein", "code": "LIE"},
  {"name": "Lithuania", "code": "LTU"},
  {"name": "Luxembourg", "code": "LUX"},
  {"name": "Macedonia (FYROM)", "code": "MKD"},
  {"name": "Madagascar", "code": "MDG"},
  {"name": "Malawi", "code": "MWI"},
  {"name": "Malaysia", "code": "MYS"},
  {"name": "Maldives", "code": "MDV"},
  {"name": "Mali", "code": "MLI"},
  {"name": "Malta", "code": "MLT"},
  {"name": "Marshall Islands", "code": "MHL"},
  {"name": "Mauritania", "code": "MRT"},
  {"name": "Mauritius", "code": "MUS"},
  {"name": "Mexico", "code": "MEX"},
  {"name": "Micronesia", "code": "FSM"},
  {"name": "Moldova", "code": "MDA"},
  {"name": "Monaco", "code": "MCO"},
  {"name": "Mongolia", "code": "MNG"},
  {"name": "Montenegro", "code": "MNE"},
  {"name": "Morocco", "code": "MAR"},
  {"name": "Mozambique", "code": "MOZ"},
  {"name": "Myanmar", "code": "MMR"},
  {"name": "Namibia", "code": "NAM"},
  {"name": "Nauru", "code": "NRU"},
  {"name": "Nepal", "code": "NPL"},
  {"name": "Netherlands", "code": "NLD"},
  {"name": "New Zealand", "code": "NZL"},
  {"name": "Nicaragua", "code": "NIC"},
  {"name": "Niger", "code": "NER"},
  {"name": "Nigeria", "code": "NGA"},
  {"name": "North Macedonia", "code": "MKD"},
  {"name": "Norway", "code": "NOR"},
  {"name": "Oman", "code": "OMN"},
  {"name": "Pakistan", "code": "PAK"},
  {"name": "Palau", "code": "PLW"},
  {"name": "Panama", "code": "PAN"},
  {"name": "Papua New Guinea", "code": "PNG"},
  {"name": "Paraguay", "code": "PRY"},
  {"name": "Peru", "code": "PER"},
  {"name": "Philippines", "code": "PHL"},
  {"name": "Poland", "code": "POL"},
  {"name": "Portugal", "code": "PRT"},
  {"name": "Qatar", "code": "QAT"},
  {"name": "Romania", "code": "ROU"},
  {"name": "Russia", "code": "RUS"},
  {"name": "Rwanda", "code": "RWA"},
  {"name": "Saint Kitts and Nevis", "code": "KNA"},
  {"name": "Saint Lucia", "code": "LCA"},
  {"name": "Saint Vincent and the Grenadines", "code": "VCT"},
  {"name": "Samoa", "code": "WSM"},
  {"name": "San Marino", "code": "SMR"},
  {"name": "Sao Tome and Principe", "code": "STP"},
  {"name": "Saudi Arabia", "code": "SAU"},
  {"name": "Senegal", "code": "SEN"},
  {"name": "Serbia", "code": "SRB"},
  {"name": "Seychelles", "code": "SYC"},
  {"name": "Sierra Leone", "code": "SLE"},
  {"name": "Singapore", "code": "SGP"},
  {"name": "Sint Maarten", "code": "SXM"},
  {"name": "Slovakia", "code": "SVK"},
  {"name": "Slovenia", "code": "SVN"},
  {"name": "Solomon Islands", "code": "SLB"},
  {"name": "Somalia", "code": "SOM"},
  {"name": "South Africa", "code": "ZAF"},
  {"name": "South Korea", "code": "KOR"},
  {"name": "South Sudan", "code": "SSD"},
  {"name": "Spain", "code": "ESP"},
  {"name": "Sri Lanka", "code": "LKA"},
  {"name": "Sudan", "code": "SDN"},
  {"name": "Suriname", "code": "SUR"},
  {"name": "Sweden", "code": "SWE"},
  {"name": "Switzerland", "code": "CHE"},
  {"name": "Syria", "code": "SYR"},
  {"name": "Tajikistan", "code": "TJK"},
  {"name": "Tanzania", "code": "TZA"},
  {"name": "Thailand", "code": "THA"},
  {"name": "Timor-Leste", "code": "TLS"},
  {"name": "Togo", "code": "TGO"},
  {"name": "Tonga", "code": "TON"},
  {"name": "Trinidad and Tobago", "code": "TTO"},
  {"name": "Tunisia", "code": "TUN"},
  {"name": "Turkey", "code": "TUR"},
  {"name": "Turkmenistan", "code": "TKM"},
  {"name": "Tuvalu", "code": "TUV"},
  {"name": "Uganda", "code": "UGA"},
  {"name": "Ukraine", "code": "UKR"},
  {"name": "United Arab Emirates", "code": "ARE"},
  {"name": "United Kingdom", "code": "GBR"},
  {"name": "United States", "code": "USA"},
  {"name": "Uruguay", "code": "URY"},
  {"name": "Uzbekistan", "code": "UZB"},
  {"name": "Vanuatu", "code": "VUT"},
  {"name": "Vatican City", "code": "VAT"},
  {"name": "Venezuela", "code": "VEN"},
  {"name": "Vietnam", "code": "VNM"},
  {"name": "Yemen", "code": "YEM"},
  {"name": "Zambia", "code": "ZMB"},
  {"name": "Zimbabwe", "code": "ZWE"}
];

List<Map<String, dynamic>> countriesCoordinates = [
  {
    'country': 'Afghanistan',
    'latitude': 33.9391,
    'longitude': 67.7100,
  },
  {
    'country': 'Albania',
    'latitude': 41.1533,
    'longitude': 20.1683,
  },
  {
    'country': 'Algeria',
    'latitude': 28.0339,
    'longitude': 1.6596,
  },
  {
    'country': 'Andorra',
    'latitude': 42.5078,
    'longitude': 1.5211,
  },
  {
    'country': 'Angola',
    'latitude': -11.2027,
    'longitude': 17.8739,
  },
  {
    'country': 'Antigua and Barbuda',
    'latitude': 17.0608,
    'longitude': -61.7964,
  },
  {
    'country': 'Argentina',
    'latitude': -38.4161,
    'longitude': -63.6167,
  },
  {
    'country': 'Armenia',
    'latitude': 40.0691,
    'longitude': 45.0382,
  },
  {
    'country': 'Australia',
    'latitude': -25.2744,
    'longitude': 133.7751,
  },
  {
    'country': 'Austria',
    'latitude': 47.5162,
    'longitude': 14.5501,
  },
  {
    'country': 'Azerbaijan',
    'latitude': 40.1431,
    'longitude': 47.5769,
  },
  {
    'country': 'Bahamas',
    'latitude': 25.0343,
    'longitude': -77.3963,
  },
  {
    'country': 'Bahrain',
    'latitude': 25.9304,
    'longitude': 50.6378,
  },
  {
    'country': 'Bangladesh',
    'latitude': 23.685,
    'longitude': 90.3563,
  },
  {
    'country': 'Barbados',
    'latitude': 13.1939,
    'longitude': -59.5432,
  },
  {
    'country': 'Belarus',
    'latitude': 53.9,
    'longitude': 27.5667,
  },
  {
    'country': 'Belgium',
    'latitude': 50.8503,
    'longitude': 4.3517,
  },
  {
    'country': 'Belize',
    'latitude': 17.1899,
    'longitude': -88.4976,
  },
  {
    'country': 'Benin',
    'latitude': 9.3075,
    'longitude': 2.3158,
  },
  {
    'country': 'Bhutan',
    'latitude': 27.5142,
    'longitude': 90.4336,
  },
  {
    'country': 'Bolivia',
    'latitude': -16.2902,
    'longitude': -63.5887,
  },
  {
    'country': 'Bosnia and Herzegovina',
    'latitude': 43.9159,
    'longitude': 17.6791,
  },
  {
    'country': 'Botswana',
    'latitude': -22.3285,
    'longitude': 24.6849,
  },
  {
    'country': 'Brazil',
    'latitude': -14.2350,
    'longitude': -51.9253,
  },
  {
    'country': 'Brunei',
    'latitude': 4.5353,
    'longitude': 114.7277,
  },
  {
    'country': 'Bulgaria',
    'latitude': 42.7339,
    'longitude': 25.4858,
  },
  {
    'country': 'Burkina Faso',
    'latitude': 12.2383,
    'longitude': -1.5616,
  },
  {
    'country': 'Burundi',
    'latitude': -3.3731,
    'longitude': 29.9189,
  },
  {
    'country': 'Cabo Verde',
    'latitude': 16.5388,
    'longitude': -23.0418,
  },
  {
    'country': 'Cambodia',
    'latitude': 12.5657,
    'longitude': 104.9910,
  },
  {
    'country': 'Cameroon',
    'latitude': 3.8480,
    'longitude': 11.5021,
  },
  {
    'country': 'Canada',
    'latitude': 56.1304,
    'longitude': -106.3468,
  },
  {
    'country': 'Central African Republic',
    'latitude': 6.6111,
    'longitude': 20.9394,
  },
  {
    'country': 'Chad',
    'latitude': 15.4542,
    'longitude': 18.7322,
  },
  {
    'country': 'Chile',
    'latitude': -35.6751,
    'longitude': -71.5430,
  },
  {
    'country': 'China',
    'latitude': 35.8617,
    'longitude': 104.1954,
  },
  {
    'country': 'Colombia',
    'latitude': 4.5709,
    'longitude': -74.2973,
  },
  {
    'country': 'Comoros',
    'latitude': -11.8751,
    'longitude': 43.8722,
  },
  {
    'country': 'Congo (Congo-Brazzaville)',
    'latitude': -0.2280,
    'longitude': 15.8270,
  },
  {
    'country': 'Congo (Democratic Republic of the Congo)',
    'latitude': -4.0383,
    'longitude': 21.7587,
  },
  {
    'country': 'Costa Rica',
    'latitude': 9.7489,
    'longitude': -83.7534,
  },
  {
    'country': 'Croatia',
    'latitude': 45.1,
    'longitude': 15.2,
  },
  {
    'country': 'Cuba',
    'latitude': 21.5218,
    'longitude': -77.7812,
  },
  {
    'country': 'Cyprus',
    'latitude': 35.1264,
    'longitude': 33.4299,
  },
  {
    'country': 'Czech Republic',
    'latitude': 49.8175,
    'longitude': 15.4729,
  },
  {
    'country': 'Denmark',
    'latitude': 56.2639,
    'longitude': 9.5018,
  },
  {
    'country': 'Djibouti',
    'latitude': 11.8251,
    'longitude': 42.5903,
  },
  {
    'country': 'Dominica',
    'latitude': 15.4149,
    'longitude': -61.3701,
  },
  {
    'country': 'Dominican Republic',
    'latitude': 18.7357,
    'longitude': -70.1627,
  },
  {
    'country': 'Ecuador',
    'latitude': -1.8312,
    'longitude': -78.1834,
  },
  {
    'country': 'Egypt',
    'latitude': 26.8206,
    'longitude': 30.8025,
  },
  {
    'country': 'El Salvador',
    'latitude': 13.7942,
    'longitude': -88.8965,
  },
  {
    'country': 'Equatorial Guinea',
    'latitude': 1.6500,
    'longitude': 10.2679,
  },
  {
    'country': 'Eritrea',
    'latitude': 15.1794,
    'longitude': 39.7823,
  },
  {
    'country': 'Estonia',
    'latitude': 58.5953,
    'longitude': 25.0136,
  },
  {
    'country': 'Eswatini',
    'latitude': -26.5225,
    'longitude': 31.4659,
  },
  {
    'country': 'Ethiopia',
    'latitude': 9.145,
    'longitude': 40.4897,
  },
  {
    'country': 'Fiji',
    'latitude': -16.5782,
    'longitude': 179.4144,
  },
  {
    'country': 'Finland',
    'latitude': 61.9241,
    'longitude': 25.7482,
  },
  {
    'country': 'France',
    'latitude': 46.6034,
    'longitude': 1.8883,
  },
  {
    'country': 'Gabon',
    'latitude': -0.8037,
    'longitude': 11.6094,
  },
  {
    'country': 'Gambia',
    'latitude': 13.4432,
    'longitude': -15.3101,
  },
  {
    'country': 'Georgia',
    'latitude': 42.3154,
    'longitude': 43.3569,
  },
  {
    'country': 'Germany',
    'latitude': 51.1657,
    'longitude': 10.4515,
  },
  {
    'country': 'Ghana',
    'latitude': 7.9465,
    'longitude': -1.0232,
  },
  {
    'country': 'Greece',
    'latitude': 39.0742,
    'longitude': 21.8243,
  },
  {
    'country': 'Grenada',
    'latitude': 12.2628,
    'longitude': -61.6042,
  },
  {
    'country': 'Guatemala',
    'latitude': 15.7835,
    'longitude': -90.2308,
  },
  {
    'country': 'Guinea',
    'latitude': 9.9456,
    'longitude': -9.6966,
  },
  {
    'country': 'Guinea-Bissau',
    'latitude': 11.8037,
    'longitude': -15.1804,
  },
  {
    'country': 'Guyana',
    'latitude': 4.8604,
    'longitude': -58.9302,
  },
  {
    'country': 'Haiti',
    'latitude': 18.9712,
    'longitude': -72.2852,
  },
  {
    'country': 'Honduras',
    'latitude': 13.9094,
    'longitude': -83.3790,
  },
  {
    'country': 'Hungary',
    'latitude': 47.1625,
    'longitude': 19.5033,
  },
  {
    'country': 'Iceland',
    'latitude': 64.9631,
    'longitude': -19.0208,
  },
  {
    'country': 'India',
    'latitude': 20.5937,
    'longitude': 78.9629,
  },
  {
    'country': 'Indonesia',
    'latitude': -0.7893,
    'longitude': 113.9213,
  },
  {
    'country': 'Iran',
    'latitude': 32.4279,
    'longitude': 53.6880,
  },
  {
    'country': 'Iraq',
    'latitude': 33.2232,
    'longitude': 43.6793,
  },
  {
    'country': 'Ireland',
    'latitude': 53.4129,
    'longitude': -8.2439,
  },
  {
    'country': 'Israel',
    'latitude': 31.4680,
    'longitude': 35.3320,
  },
  {
    'country': 'Italy',
    'latitude': 41.8719,
    'longitude': 12.5674,
  },
  {
    'country': 'Jamaica',
    'latitude': 18.1096,
    'longitude': -77.2975,
  },
  {
    'country': 'Japan',
    'latitude': 36.2048,
    'longitude': 138.2529,
  },
  {
    'country': 'Jordan',
    'latitude': 30.5852,
    'longitude': 36.2384,
  },
  {
    'country': 'Kazakhstan',
    'latitude': 48.0196,
    'longitude': 66.9237,
  },
  {
    'country': 'Kenya',
    'latitude': -1.2921,
    'longitude': 36.8219,
  },
  {
    'country': 'Kiribati',
    'latitude': -3.3704,
    'longitude': -168.7340,
  },
  {
    'country': 'Korea, North',
    'latitude': 40.3399,
    'longitude': 127.5101,
  },
  {
    'country': 'Korea, South',
    'latitude': 35.9078,
    'longitude': 127.7669,
  },
  {
    'country': 'Kuwait',
    'latitude': 29.3759,
    'longitude': 47.9774,
  },
  {
    'country': 'Kyrgyzstan',
    'latitude': 41.2044,
    'longitude': 74.7661,
  },
  {
    'country': 'Laos',
    'latitude': 19.8563,
    'longitude': 102.4955,
  },
  {
    'country': 'Latvia',
    'latitude': 56.8796,
    'longitude': 24.6032,
  },
  {
    'country': 'Lebanon',
    'latitude': 33.8547,
    'longitude': 35.8623,
  },
  {
    'country': 'Lesotho',
    'latitude': -29.6093,
    'longitude': 28.2336,
  },
  {
    'country': 'Liberia',
    'latitude': 6.4281,
    'longitude': -9.4295,
  },
  {
    'country': 'Libya',
    'latitude': 26.3351,
    'longitude': 17.2283,
  },
  {
    'country': 'Liechtenstein',
    'latitude': 47.1415,
    'longitude': 9.5215,
  },
  {
    'country': 'Lithuania',
    'latitude': 55.1694,
    'longitude': 23.8813,
  },
  {
    'country': 'Luxembourg',
    'latitude': 49.6117,
    'longitude': 6.13,
  },
  {
    'country': 'Madagascar',
    'latitude': -18.7669,
    'longitude': 46.8691,
  },
  {
    'country': 'Malawi',
    'latitude': -13.2543,
    'longitude': 34.3015,
  },
  {
    'country': 'Malaysia',
    'latitude': 4.2105,
    'longitude': 101.9758,
  },
  {
    'country': 'Maldives',
    'latitude': 3.2028,
    'longitude': 73.2207,
  },
  {
    'country': 'Mali',
    'latitude': 17.5707,
    'longitude': -3.9962,
  },
  {
    'country': 'Malta',
    'latitude': 35.9375,
    'longitude': 14.3754,
  },
  {
    'country': 'Marshall Islands',
    'latitude': 7.1315,
    'longitude': 171.1845,
  },
  {
    'country': 'Mauritania',
    'latitude': 21.0079,
    'longitude': -10.9400,
  },
  {
    'country': 'Mauritius',
    'latitude': -20.3484,
    'longitude': 57.5522,
  },
  {
    'country': 'Mexico',
    'latitude': 23.6345,
    'longitude': -102.5528,
  },
  {
    'country': 'Micronesia',
    'latitude': 7.4256,
    'longitude': 150.5508,
  },
  {
    'country': 'Moldova',
    'latitude': 47.4116,
    'longitude': 28.3699,
  },
  {
    'country': 'Monaco',
    'latitude': 43.7333,
    'longitude': 7.4167,
  },
  {
    'country': 'Mongolia',
    'latitude': 46.8625,
    'longitude': 103.8467,
  },
  {
    'country': 'Montenegro',
    'latitude': 42.7087,
    'longitude': 19.3744,
  },
  {
    'country': 'Morocco',
    'latitude': 31.7917,
    'longitude': -7.0926,
  },
  {
    'country': 'Mozambique',
    'latitude': -18.6657,
    'longitude': 35.5296,
  },
  {
    'country': 'Myanmar',
    'latitude': 21.9139,
    'longitude': 95.9560,
  },
  {
    'country': 'Namibia',
    'latitude': -22.9576,
    'longitude': 18.4904,
  },
  {
    'country': 'Nauru',
    'latitude': -0.5228,
    'longitude': 166.9315,
  },
  {
    'country': 'Nepal',
    'latitude': 28.3949,
    'longitude': 84.1240,
  },
  {
    'country': 'Netherlands',
    'latitude': 52.1326,
    'longitude': 5.2913,
  },
  {
    'country': 'New Zealand',
    'latitude': -40.9006,
    'longitude': 174.8860,
  },
  {
    'country': 'Nicaragua',
    'latitude': 12.8654,
    'longitude': -85.2072,
  },
  {
    'country': 'Niger',
    'latitude': 17.6078,
    'longitude': 8.0817,
  },
  {
    'country': 'Nigeria',
    'latitude': 9.0820,
    'longitude': 8.6753,
  },
  {
    'country': 'North Macedonia',
    'latitude': 41.6086,
    'longitude': 21.7453,
  },
  {
    'country': 'Norway',
    'latitude': 60.4720,
    'longitude': 8.4689,
  },
  {
    'country': 'Oman',
    'latitude': 21.5126,
    'longitude': 55.9233,
  },
  {
    'country': 'Pakistan',
    'latitude': 30.3753,
    'longitude': 69.3451,
  },
  {
    'country': 'Palau',
    'latitude': 7.5149,
    'longitude': 134.5825,
  },
  {
    'country': 'Panama',
    'latitude': 8.5375,
    'longitude': -80.7821,
  },
  {
    'country': 'Papua New Guinea',
    'latitude': -6.3149,
    'longitude': 143.9555,
  },
  {
    'country': 'Paraguay',
    'latitude': -23.4425,
    'longitude': -58.4438,
  },
  {
    'country': 'Peru',
    'latitude': -9.19,
    'longitude': -75.0152,
  },
  {
    'country': 'Philippines',
    'latitude': 12.8797,
    'longitude': 121.7740,
  },
  {
    'country': 'Poland',
    'latitude': 51.9194,
    'longitude': 19.1451,
  },
  {
    'country': 'Portugal',
    'latitude': 39.3999,
    'longitude': -8.2245,
  },
  {
    'country': 'Qatar',
    'latitude': 25.3548,
    'longitude': 51.1839,
  },
  {
    'country': 'Romania',
    'latitude': 45.9432,
    'longitude': 24.9668,
  },
  {
    'country': 'Russia',
    'latitude': 55.7558,
    'longitude': 37.6176,
  },
  {
    'country': 'Rwanda',
    'latitude': -1.9403,
    'longitude': 29.8739,
  },
  {
    'country': 'Saint Kitts and Nevis',
    'latitude': 17.3578,
    'longitude': -62.7820,
  },
  {
    'country': 'Saint Lucia',
    'latitude': 13.9094,
    'longitude': -60.9780,
  },
  {
    'country': 'Saint Vincent and the Grenadines',
    'latitude': 12.9843,
    'longitude': -61.2872,
  },
  {
    'country': 'Samoa',
    'latitude': -13.7590,
    'longitude': -172.1046,
  },
  {
    'country': 'San Marino',
    'latitude': 43.9333,
    'longitude': 12.45,
  },
  {
    'country': 'Sao Tome and Principe',
    'latitude': 0.1864,
    'longitude': 6.6131,
  },
  {
    'country': 'Saudi Arabia',
    'latitude': 23.8859,
    'longitude': 45.0792,
  },
  {
    'country': 'Senegal',
    'latitude': 14.6928,
    'longitude': -14.0079,
  },
  {
    'country': 'Serbia',
    'latitude': 44.0165,
    'longitude': 21.0059,
  },
  {
    'country': 'Seychelles',
    'latitude': -4.6796,
    'longitude': 55.4920,
  },
  {
    'country': 'Sierra Leone',
    'latitude': 8.4606,
    'longitude': -11.7799,
  },
  {
    'country': 'Singapore',
    'latitude': 1.3521,
    'longitude': 103.8198,
  },
  {
    'country': 'Slovakia',
    'latitude': 48.6690,
    'longitude': 19.6990,
  },
  {
    'country': 'Slovenia',
    'latitude': 46.1511,
    'longitude': 14.9955,
  },
  {
    'country': 'Solomon Islands',
    'latitude': -29.7681,
    'longitude': 152.3458,
  },
  {
    'country': 'Somalia',
    'latitude': 5.1521,
    'longitude': 46.1996,
  },
  {
    'country': 'South Africa',
    'latitude': -30.5595,
    'longitude': 22.9375,
  },
  {
    'country': 'South Sudan',
    'latitude': 6.8777,
    'longitude': 31.3070,
  },
  {
    'country': 'Spain',
    'latitude': 40.4637,
    'longitude': -3.7492,
  },
  {
    'country': 'Sri Lanka',
    'latitude': 7.8731,
    'longitude': 80.7718,
  },
  {
    'country': 'Sudan',
    'latitude': 12.8628,
    'longitude': 30.8025,
  },
  {
    'country': 'Suriname',
    'latitude': 3.9193,
    'longitude': -56.0278,
  },
  {
    'country': 'Sweden',
    'latitude': 60.1282,
    'longitude': 18.6435,
  },
  {
    'country': 'Switzerland',
    'latitude': 46.8182,
    'longitude': 8.2275,
  },
  {
    'country': 'Syria',
    'latitude': 34.8021,
    'longitude': 38.9968,
  },
  {
    'country': 'Taiwan',
    'latitude': 23.6978,
    'longitude': 120.9605,
  },
  {
    'country': 'Tajikistan',
    'latitude': 38.8610,
    'longitude': 71.2761,
  },
  {
    'country': 'Tanzania',
    'latitude': -6.369028,
    'longitude': 34.888822,
  },
  {
    'country': 'Thailand',
    'latitude': 15.8700,
    'longitude': 100.9925,
  },
  {
    'country': 'Timor-Leste',
    'latitude': -8.8742,
    'longitude': 125.7275,
  },
  {
    'country': 'Togo',
    'latitude': 8.6195,
    'longitude': 0.8248,
  },
  {
    'country': 'Tonga',
    'latitude': -21.1789,
    'longitude': -175.1982,
  },
  {
    'country': 'Trinidad and Tobago',
    'latitude': 10.6918,
    'longitude': -61.2225,
  },
  {
    'country': 'Tunisia',
    'latitude': 33.8869,
    'longitude': 9.5375,
  },
  {
    'country': 'Turkey',
    'latitude': 38.9637,
    'longitude': 35.2433,
  },
  {
    'country': 'Turkmenistan',
    'latitude': 38.9697,
    'longitude': 59.5563,
  },
  {
    'country': 'Tuvalu',
    'latitude': -7.1095,
    'longitude': 177.6493,
  },
  {
    'country': 'Uganda',
    'latitude': 1.3733,
    'longitude': 32.2903,
  },
  {
    'country': 'Ukraine',
    'latitude': 48.3794,
    'longitude': 31.1656,
  },
  {
    "country": "United Arab Emirates",
    "latitude": 23.4241,
    "longitude": 53.8478
  },
  {"country": "United Kingdom", "latitude": 55.3781, "longitude": -3.4360},
  {"country": "United States", "latitude": 37.0902, "longitude": -95.7129},
  {"country": "Uruguay", "latitude": -32.5228, "longitude": -55.7658},
  {"country": "Uzbekistan", "latitude": 41.3775, "longitude": 64.5850},
  {"country": "Vanuatu", "latitude": -15.3767, "longitude": 167.5197},
  {"country": "Vatican City", "latitude": 41.9029, "longitude": 12.4534},
  {"country": "Venezuela", "latitude": 6.4238, "longitude": -66.5897},
  {"country": "Vietnam", "latitude": 14.0583, "longitude": 108.2772},
  {"country": "Yemen", "latitude": 15.5521, "longitude": 48.5164},
  {"country": "Zambia", "latitude": -13.1339, "longitude": 27.8493},
  {"country": "Zimbabwe", "latitude": -19.0154, "longitude": 29.1549}
];
